### ISSUE TITLE
有人一起做吗，咱们建个微信群讨论吧，

### ISSUE THREAD

**Issue by jingrunzhou** [wusaifei/garbage_classify#38]

**Comment by wusaifei** [comment]
代码已经更新了简单版本的分类和目标检测代码，可以看一下。

**Comment by ziduGithub** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    好的，谢谢您！
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1692886559
                            
                    
                        
                            
                                    1692886559@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年7月16日 15:32，仵赛飞<notifications@github.com> 写道： 




代码已经更新了简单版本的分类和目标检测代码，可以看一下。



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ziduGithub** [comment]
> 有人一起做吗，咱们建个微信群讨论吧，加我微信：z1692886559

**Comment by refugge** [comment]
好呀，微信群二维码可以发给我哦

发自我的iPhone
